CREATE TABLE ADMIN 
(
  USERID VARCHAR2(100 BYTE) NOT NULL 
, PASSWORD VARCHAR2(100 BYTE) NOT NULL 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

ALTER TABLE ADMIN
ADD CONSTRAINT USER_CONS UNIQUE 
(
  USERID 
)
USING INDEX 
(
    CREATE UNIQUE INDEX USER_CONS ON ADMIN (USERID ASC) 
    LOGGING 
    TABLESPACE SYSTEM 
    PCTFREE 10 
    INITRANS 2 
    STORAGE 
    ( 
      INITIAL 65536 
      NEXT 1048576 
      MINEXTENTS 1 
      MAXEXTENTS UNLIMITED 
      FREELISTS 1 
      FREELIST GROUPS 1 
      BUFFER_POOL DEFAULT 
    ) 
    NOPARALLEL 
)
 ENABLE;