CREATE TABLE BILL_POLLING 
(
  BILL_ID VARCHAR2(20 BYTE) NOT NULL 
, GROUP_MEMBER VARCHAR2(20 BYTE) NOT NULL 
, POLLING NUMBER(1, 0) NOT NULL 
, GROUP_ID VARCHAR2(20 BYTE) NOT NULL 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

ALTER TABLE BILL_POLLING
ADD CONSTRAINT BILL_ID_PK FOREIGN KEY
(
  BILL_ID 
)
REFERENCES BILL_DETAIL
(
  BILL_ID 
)
ON DELETE CASCADE ENABLE;

ALTER TABLE BILL_POLLING
ADD CONSTRAINT BILL_POLLING_FK FOREIGN KEY
(
  GROUP_MEMBER 
)
REFERENCES USER_DETAIL
(
  EMAIL 
)
ON DELETE CASCADE ENABLE;