CREATE TABLE BILL_DETAIL 
(
  GROUP_MEMBER VARCHAR2(100 BYTE) NOT NULL 
, GROUP_ID VARCHAR2(100 BYTE) NOT NULL 
, DESCRIPTION VARCHAR2(4000 BYTE) NOT NULL 
, AMOUNT NUMBER(*, 0) NOT NULL 
, ACCEPTED NUMBER(1, 0) NOT NULL 
, BILL_ID VARCHAR2(20 BYTE) NOT NULL 
, DATE_ADDED DATE 
, MONTH_ADDED NUMBER 
, YEAR_ADDED NUMBER 
, CONSTRAINT BILL_DETAIL_PK PRIMARY KEY 
  (
    BILL_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX BILL_DETAIL_PK ON BILL_DETAIL (BILL_ID ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

ALTER TABLE BILL_DETAIL
ADD CONSTRAINT BILL_DETAIL_FK FOREIGN KEY
(
  GROUP_ID 
)
REFERENCES GROUP_HEAD
(
  GROUP_ID 
)
ON DELETE CASCADE ENABLE;

ALTER TABLE BILL_DETAIL
ADD CONSTRAINT BILL_DETAIL_FK1 FOREIGN KEY
(
  GROUP_MEMBER 
)
REFERENCES USER_DETAIL
(
  EMAIL 
)
ON DELETE CASCADE ENABLE;