CREATE TABLE GROUP_MEMBER 
(
  GROUP_NAME VARCHAR2(100 BYTE) NOT NULL 
, GROUP_ID VARCHAR2(100 BYTE) NOT NULL 
, GROUP_MEMBER VARCHAR2(100 BYTE) NOT NULL 
, ACTIVE NUMBER(1, 0) NOT NULL 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

ALTER TABLE GROUP_MEMBER
ADD CONSTRAINT GROUP_ID_PK FOREIGN KEY
(
  GROUP_ID 
)
REFERENCES GROUP_HEAD
(
  GROUP_ID 
)
ON DELETE CASCADE ENABLE;

ALTER TABLE GROUP_MEMBER
ADD CONSTRAINT GROUP_MEMBER_FK FOREIGN KEY
(
  GROUP_MEMBER 
)
REFERENCES USER_DETAIL
(
  EMAIL 
)
ON DELETE CASCADE ENABLE;
