CREATE TABLE GROUP_HEAD 
(
  GROUP_NAME VARCHAR2(100 BYTE) NOT NULL 
, GROUP_ID VARCHAR2(100 BYTE) NOT NULL 
, GROUP_HEAD VARCHAR2(100 BYTE) NOT NULL 
, ACTIVE NUMBER(1, 0) NOT NULL 
, CONSTRAINT GROUP_HEAD_PK PRIMARY KEY 
  (
    GROUP_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX GROUP_HEAD_PK ON GROUP_HEAD (GROUP_ID ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

ALTER TABLE GROUP_HEAD
ADD CONSTRAINT GROUP_HEAD_FK FOREIGN KEY
(
  GROUP_HEAD 
)
REFERENCES USER_DETAIL
(
  EMAIL 
)
ON DELETE CASCADE ENABLE;
