CREATE TABLE USER_DETAIL 
(
  NAME VARCHAR2(100 BYTE) NOT NULL 
, EMAIL VARCHAR2(100 BYTE) NOT NULL 
, PASSWORD VARCHAR2(100 BYTE) NOT NULL 
, MOBILE_NO NUMBER 
, CONSTRAINT USER_DETAIL_PK PRIMARY KEY 
  (
    EMAIL 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX USER_DETAIL_PK ON USER_DETAIL (EMAIL ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;
